import { createElement } from 'lwc';
import CallApexClassWithWireProperty02 from 'c/callApexClassWithWireProperty02';

describe('c-call-apex-class-with-wire-property02', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-call-apex-class-with-wire-property02', {
            is: CallApexClassWithWireProperty02
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});